# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-03 09:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20180403_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Mobile',
            new_name='Phone',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Belongto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
